### PR TITLE
move contributing files to .github

### PR DESCRIPTION
**Pull request by elordahl**
Creating this folder in case you decide to add PR and/or Issue templates.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Interesting, what does moving to `.github` do? I don't think I've seen this before.

**Comment by elordahl** [comment]
to my knowledge, the files are treated the same.  it's just a way to keep the repository tidy by storing the CODE_OF_CONDUCT, CONTRIBUTING, SUPPORT, ISSUE_TEMPLATE, and  PULL_REQUEST_TEMPLATE files in a single folder (which is hidden locally as a dot-folder).

https://github.blog/2016-02-17-issue-and-pull-request-templates/

They can also be applied to all public repositories in an organization by [creating a **.github** repository](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization) for that org.

**Comment by galtay** [comment]
Another thing I noticed, the repo doesn't reognize the `CODE_OF_CONDUCT.rst` file (in the insights/community tab it still suggests that we create one).  I wrote the README in rst to be consistent with the sphinx docs, and readthdocs + pypi needs to know the format of the README to render it properly.  I think we can make the other files markdown and make github happy (and probably gather them into a `.github` directory.

**Comment by obi1kenobi** [comment]
I don't know about readthedocs, but PyPI is happy with Markdown if you tell it the format is Markdown -- we've set it up successfully in the GraphQL compiler project.

**Comment by galtay** [comment]
Both PyPI and readthedocs are happy with markdown if you tell them to use markdown, but you cant include the README file in the index.rst file for sphinx if you use markdown.

**Pull request merged**
