### PR TITLE
Accept jsonl/ndjson files

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
Allow jsonl/ndjson files.

### CODE REVIEW

**Comment by galtay** [comment]
Thanks for the PR Sultan.  Do you have examples/links to files with `jsonl` and `ndjson` extensions provided by Wikidata?   Currently, the `WikidataJsonDump` class docstring reads, 

```
    Represents a json file from https://dumps.wikimedia.org/wikidatawiki/entities.
    File names are of the form "wikidata-YYYYMMDD-all.json[.bz2|.gz]".  The file is a single JSON
    array and there is one element (i.e. item or property) on each line with the first and
    last lines being the opening and closing square brackets.  This class can handle bz2 or gz
    compressed files as well as the uncompressed json files.

    Parameters
    ----------
    filename: str
      The wikidata JSON dump file name (e.g. `my_data_dir/wikidata-20180730-all.json.bz2`)
```

We'd need to make sure that the iterators and all the other functionality of the class still works with these file formats and then update the docs accordingly.

**Comment by SultanOrazbayev** [comment]
I will need a bit more time to experiment with this, the `jsonl`/`ndjson` are coming out from an external pipeline, but I'll include a couple of examples in the next request.

**Comment by galtay** [comment]
no problem.  also feel free to create an issue if you'd like.

**Review by galtay — CHANGES_REQUESTED** [review]
We'd need to make sure that the iterators and all the other functionality of the class still works with these file formats and then update the docs accordingly.

**Comment by galtay** [comment]
closing for now

**Pull request closed without merging**
