### PR TITLE
Update json_dump.py

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
Changes to allow loading of jsonl chunks.

### CODE REVIEW

**Comment by SultanOrazbayev** [comment]
When encountering problems with some chunks, I wanted to load specific chunks, but since they were in jsonl, couldn't open them.

**Comment by galtay** [comment]
I see the problem, however the `WikidataJsonDump` class is meant to read the files provided by wikimedia.  If we allow `jsonl` files as input, the iterator for the class will not work correctly.  It expects a traditional json array in the file.  It also might be confusing to use a class with `Json` in the name to read `Jsonl` files.  It might be best to remove the jsonl output feature until the input and iteration can handle it.  Would your workflow be ruined if you had to use json chunks as opposed to jsonl chunks?

**Comment by SultanOrazbayev** [comment]
Ah, no, it's only a minor thing, I am working with both formats. Just thought for consistency, it would be nice to open `jsonl` chunks. I didn't realise there would be an issue with the iterator.

**Comment by galtay** [comment]
I might add another class called `WikidataJsonlDump` that handles those so that you can use an instance of `WikidataJsonDump` to produce jsonl chunks and then read them with an instance of `WikidataJsonlDump`. I do like the jsonl format :)

**Comment by galtay** [comment]
For now I'll remove the `jsonl` functionality so folks don't get into a place where they cant read the chunks.

**Comment by SultanOrazbayev** [comment]
Sounds good!

**Pull request closed without merging**
