### PR TITLE
Modify dump_entities_to_json method

### LINKED ISSUE #29: dump_entities_to_json fails if entities has only one member
https://github.com/kensho-technologies/qwikidata/blob/develop/qwikidata/utils.py#L33

`ent_hi` will be undefined

### PR DESCRIPTION
**Pull request by kunaltawatia**
fixes kensho-technologies/qwikidata#29

### CODE REVIEW

**Review by galtay — APPROVED** [review]
looks good. thanks for the contribution!

**Review by galtay — CHANGES_REQUESTED** [review]
One last thing, would you mind adding a minor version bump to `0.4.1` here https://github.com/kensho-technologies/qwikidata/blob/develop/qwikidata/__init__.py

**Review by galtay — APPROVED** [review]
Great work. Thanks for the fix. :tada:

**Comment by kunaltawatia** [comment]
Thanks for allowing me. It was nice working with you.

**Pull request merged**
